#ifndef MEASURE_PARAMETERS_H
#define MEASURE_PARAMETERS_H

extern const Parameters_measure measure_P_50Hz_80_samples_per_cycle;
extern const Parameters_measure measure_P_60Hz_80_samples_per_cycle;
extern const Parameters_measure measure_P_50Hz_256_samples_per_cycle;
extern const Parameters_measure measure_P_60Hz_256_samples_per_cycle;

#endif // MEASURE_PARAMETERS_H
